const actiontypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',

    LOGIN_SUCCESS:      'LOGIN_SUCCESS',
    LOGIN_FAILED:       'LOGIN_FAILED',
    LOGIN_FATAL_ERROR:  'LOGIN_FATAL_ERROR',
    
    LOGOUT_SUCCESS:     'LOGOUT_SUCCESS',

    GET_PROFILE_SUCCESS:    'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED:     'GET_PROFILE_FAILED',

    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILED:  'UPDATE_PROFILE_FAILED',

    FETCH_ALL_SALONS: 'FETCH_ALL_SALONS',
    FETCH_THIS_SALON: 'FETCH_THIS_SALON',
    FETCH_FAILED:' FETCH_FAILED',
    FETCH_START:'FETCH_START'
}

export default actiontypes